name: sync2gitee(list)
# version: 1.1.0
# author: [yiXu](https://github.com/yi-Xu-0100)
# guide: [yi-Xu-0100/hub-mirror](https://github.com/yi-Xu-0100/hub-mirror)
# template: [sync2gitee.list.yml](https://github.com/yi-Xu-0100/hub-mirror/blob/main/template/sync2gitee.list.yml)
# lastmod: 2021-02-02 10:23:02

on:
  workflow_dispatch:
  schedule:
    # UTC 17:30 -> CST (China) 1:30 see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 10 * * *'

jobs:
  run:
    name: Sync GitHub to Gitee(list)
    runs-on: ubuntu-latest
    steps:

      - name: Get repo and time
        id: info
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            core.setOutput('time', new Date(Date.now()).toISOString().replace(/[^0-9]/g, ""));
            core.setOutput('key', `${context.repo.owner}-${context.repo.repo}`);
      # - name: Cache src repos
      #   uses: actions/cache@v2.1.3
      #   id: cache
      #   with:
      #     path: ${{ github.workspace }}/hub-mirror-cache
      #     key: ${{ runner.os }}-${{ steps.info.outputs.key }}-list-cache-${{ steps.info.outputs.time }}
      #     restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-list-

      # - name: Generate repo list
      #   id: repo
      #   uses: yi-Xu-0100/repo-list-generator@v1.0.0
      #   with:
      #     user: 'Tree-Roots'

      # - name: Mark github workspace as safe
      #   run: |
      #     git config --global --add safe.directory ${{ github.workspace }}


      - name: Mirror hub with cache and list
        uses: Yikun/hub-mirror-action@v0.13
        with:
          src: github/Tree-Roots
          dst: gitee/Sonic853
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'VRChatPackages,VRChatUdonSharpPackages,VRChatClientsimPackages,VPRTPackage'
          cache_path: ${{ github.workspace }}/hub-mirror-cache
          account_type: user
          force_update: true

      - name: Print cache path
        run: |
          ls -la ${{ github.workspace }}/hub-mirror-cache
